spring:
  main:
    banner-mode: 'off'
logging:
  level:
    com.zaxxer: warn
    dev.hiberbee: debug
    io.fabric8: error
    org.springframework.cglib: error
    org.springframework: warn
    root: info
