name: Continuous Integration
on: push
jobs:
  features:
    name: Kubernetes features
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@latest
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Test features
        run: sh gradlew features
        env:
          FEATURES_DIR: ${{ github.workspace }}/features
        with:
          arguments: features
