name: Continuous Integration
on: push
jobs:
  features:
    name: Kubernetes features
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@latest
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Test features
        uses: eskatos/gradle-command-action@v1
        env:
          FEATURES_DIR: ${{ github.workspace }}/features
        with:
          arguments: features
      - name: Analyze sources with Sonarqube
        uses: eskatos/gradle-command-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          arguments: sonarqube
