name: Lint workflow
on: push
jobs:
  lint:
    name: Lint sources
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          DEFAULT_BRANCH: latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GROOVY: true
          VALIDATE_JAVA: true
